def cleanText(text):
    text = text.lower()
    text = text.replace(',','')
    text = text.replace('.','')
    text = text.replace('/','')
    text = text.replace('?','')
    text = text.replace('>','')
    text = text.replace('<','')
    text = text.replace('\'','')
    text = text.replace('\"','')
    text = text.replace(';','')
    text = text.replace(':','')
    text = text.replace('{','')
    text = text.replace('}','')
    text = text.replace('[','')
    text = text.replace(']','')
    text = text.replace('\\','')
    text = text.replace('|','')
    text = text.replace('`','')
    text = text.replace('~','')
    text = text.replace('!','')
    text = text.replace('@','')
    text = text.replace('#','')
    text = text.replace('$','')
    text = text.replace('%','')
    text = text.replace('^','')
    text = text.replace('&','')
    text = text.replace('*','')
    text = text.replace('(','')
    text = text.replace(')','')
    text = text.replace('-','')
    text = text.replace('_','')
    text = text.replace('=','')
    text = text.replace('+','')

    if text.isalnum():
        for i in range(10):
            text = text.replace(str(i),'')

    return text
